/**
 * winspect init — onboarding, spec auto-detect, CODEOWNERS, .winspect.yaml, optional register
 */

import { Command } from "commander";
import chalk from "chalk";
import { findSpecInDir } from "../lib/spec-finder.js";
import { getTeamFromCodeowners } from "../lib/codeowners.js";
import { writeFileSync } from "fs";
import { join } from "path";
import { execSync } from "child_process";

export function registerInitCommand(program: Command) {
  program
    .command("init")
    .description("Initialize Winspect config: detect spec, create .winspect.yaml, optional register")
    .option("--all", "Scan subdirectories for .winspect.yaml (monorepo)")
    .option("--publish", "Run winspect register after writing config (legacy flag name)")
    .action(async (opts: { all?: boolean; publish?: boolean }) => {
      const cwd = process.cwd();
      const specPath = findSpecInDir(cwd);
      if (!specPath) {
        console.error(chalk.red("No OpenAPI spec found. Add openapi.yaml, openapi.json, or swagger.yaml"));
        process.exit(1);
      }
      const specName = specPath.split("/").pop() ?? "openapi.yaml";
      const team = getTeamFromCodeowners(cwd, specPath);
      const defaultName = specPath.split("/").slice(-2, -1)[0] ?? "api";
      const suggestedName = defaultName.replace(/[^a-z0-9-]/gi, "-").toLowerCase();

      console.log(chalk.blue(`Found ${specName}. Suggested API name: ${suggestedName}`));
      if (team) console.log(chalk.blue(`Team from CODEOWNERS: ${team}`));

      const config = {
        spec: specName,
        name: suggestedName,
        owner: team ?? "default",
        namespace: `${team ?? "default"}/${suggestedName}`,
        autoCreateTeam: false,
        strict: false,
        checkBreaking: true,
      };

      const yamlPath = join(cwd, ".winspect.yaml");
      const yaml = [
        `# Winspect config — generated by winspect init`,
        `spec: ${specName}`,
        `name: ${config.name}`,
        `owner: ${config.owner}`,
        `namespace: ${config.namespace}`,
        `auto-create-team: ${config.autoCreateTeam}`,
        `strict: ${config.strict}`,
        `check-breaking: ${config.checkBreaking}`,
      ].join("\n");

      writeFileSync(yamlPath, yaml);
      console.log(chalk.green("Initialized! Winspect config written to .winspect.yaml"));
      if (opts.publish) {
        try {
          execSync("winspect register", { stdio: "inherit", cwd });
        } catch {
          console.error(chalk.red("Register failed. Run 'winspect register' manually."));
          process.exit(1);
        }
      } else {
        console.log(chalk.blue("Run 'winspect register' to upload your spec (or use --publish)."));
      }
    });
}
