/**
 * spec0 init — onboarding, spec auto-detect, CODEOWNERS, .spec0.yaml, optional register
 */

import { Command } from "commander";
import chalk from "chalk";
import { findSpecInDir } from "../lib/spec-finder.js";
import { getTeamFromCodeowners } from "../lib/codeowners.js";
import { writeFileSync } from "fs";
import { join } from "path";
import { execSync } from "child_process";
import { ExitCode, exit } from "../lib/exit-codes.js";

export function registerInitCommand(program: Command) {
  program
    .command("init")
    .description("Detect your OpenAPI spec and create a .spec0.yaml config file")
    .option("--all", "Scan subdirectories for .spec0.yaml (monorepo)")
    .option("--push", "Run spec0 push after writing config")
    .action(async (opts: { all?: boolean; push?: boolean }) => {
      const cwd = process.cwd();
      const specPath = findSpecInDir(cwd);
      if (!specPath) {
        console.error(
          chalk.red("No OpenAPI spec found. Add openapi.yaml, openapi.json, or swagger.yaml"),
        );
        exit(ExitCode.USAGE);
      }
      const specName = specPath.split("/").pop() ?? "openapi.yaml";
      const team = getTeamFromCodeowners(cwd, specPath);
      const defaultName = specPath.split("/").slice(-2, -1)[0] ?? "api";
      const suggestedName = defaultName.replace(/[^a-z0-9-]/gi, "-").toLowerCase();

      console.log(chalk.blue(`Found ${specName}. Suggested API name: ${suggestedName}`));
      if (team) console.log(chalk.blue(`Team from CODEOWNERS: ${team}`));

      const config = {
        spec: specName,
        name: suggestedName,
        owner: team ?? "default",
        namespace: `${team ?? "default"}/${suggestedName}`,
        autoCreateTeam: false,
        strict: false,
        checkBreaking: true,
      };

      const yamlPath = join(cwd, ".spec0.yaml");
      const yaml = [
        `# Spec0 config — generated by spec0 init`,
        `spec: ${specName}`,
        `name: ${config.name}`,
        `owner: ${config.owner}`,
        `namespace: ${config.namespace}`,
        `auto-create-team: ${config.autoCreateTeam}`,
        `strict: ${config.strict}`,
        `check-breaking: ${config.checkBreaking}`,
      ].join("\n");

      writeFileSync(yamlPath, yaml);
      console.log(chalk.green("Initialized! Spec0 config written to .spec0.yaml"));
      if (opts.push) {
        try {
          execSync("spec0 push", { stdio: "inherit", cwd });
        } catch {
          console.error(chalk.red("Push failed. Run 'spec0 push' manually."));
          exit(ExitCode.GENERIC);
        }
      } else {
        console.log(chalk.blue("Run 'spec0 push' to upload your spec (or use --push)."));
      }
    });
}
