/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api-management/cli/v1/mocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List mock servers for an org */
        get: operations["listMocks"];
        put?: never;
        /** Create or fetch default mock server for API */
        post: operations["createMock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-management/cli/v1/spectral-ruleset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get org Spectral ruleset */
        get: operations["getSpectralRuleset"];
        /** Save org Spectral ruleset */
        put: operations["putSpectralRuleset"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-management/cli/v1/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish OpenAPI spec from CLI
         * @description Publishes a design-time API spec for CLI workflows.
         *     - If `apiId` is provided: update that API metadata/spec and publish version.
         *     - If `apiId` is omitted: create a new API using `name` + `team` and publish version.
         */
        post: operations["publishCliSpec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Provide either `apiId` or `apiName`. */
        CreateMockRequest: {
            /** Format: uuid */
            apiId?: string;
            apiName?: string;
        };
        MockItem: {
            /** Format: uuid */
            mockServerId?: string;
            /** Format: uuid */
            apiId?: string;
            apiName?: string;
            name?: string;
            mockBaseUrl?: string;
        };
        CreateMockResponse: components["schemas"]["MockItem"] & {
            created?: boolean;
            /** @description One-time API key shown only when mock is newly created. */
            apiKey?: string | null;
        };
        SpectralRulesetResponse: {
            rulesetYaml?: string;
        };
        PutSpectralRulesetRequest: {
            rulesetYaml?: string;
        };
        StatusResponse: {
            status?: string;
        };
        CliPublishRequest: {
            /**
             * Format: uuid
             * @description Existing API id (backward compat). Prefer slug-based upsert via name.
             */
            apiId?: string;
            /**
             * @description API name (kebab-case). If omitted, derived from the basename of specFilePath.
             *     Never derived from info.title — title is display metadata, not the API identity.
             */
            name?: string;
            /** @description Team UUID or slug. If omitted, API lands in org's "Unassigned APIs" team. */
            team?: string;
            /** @description Semver version tag. If omitted, extracted from info.version in the spec. */
            version?: string;
            /** @description OpenAPI document content (YAML or JSON). */
            openapiSpec: string;
            /** @description Git commit SHA. Used as idempotency key — same SHA = no-op. */
            gitSha?: string;
            githubRepo?: string;
            githubBranch?: string;
            /** @description Relative path to spec file. Used to derive API name if name is omitted. */
            specFilePath?: string;
            /**
             * @description Auto-compute next version via oasdiff diff classification
             *     (PATCH / NON_BREAKING / BREAKING).
             * @default false
             */
            semver: boolean;
        };
        CliPublishResponse: {
            /** Format: uuid */
            apiId?: string;
            /** Format: uuid */
            specRecordId?: string;
            version?: string;
            /** @description True if a new API entity was created. */
            created?: boolean;
            /** @description True if a new version snapshot was created. */
            versionCreated?: boolean;
            /** @description True if git SHA matched — no changes detected, no-op. */
            noChanges?: boolean;
            /** @description Spec changed but version tag is the same as the stored HEAD. */
            versionUnchanged?: boolean;
            /** @description Human-readable hint for versionUnchanged case. */
            versionUnchangedHint?: string;
            /** @description Resolved API name. */
            apiName?: string;
            /** @description Resolved team name. */
            teamName?: string;
            /** @description Organisation slug. */
            orgSlug?: string;
            /** @description Canonical registry path (e.g. /registry/{orgSlug}/{apiName}). */
            registryUrl?: string;
        };
        Problem: {
            status?: number;
            title?: string;
            detail?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMocks: {
        parameters: {
            query?: never;
            header: {
                "X-Org-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mock servers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockItem"][];
                };
            };
        };
    };
    createMock: {
        parameters: {
            query?: never;
            header: {
                "X-Org-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMockRequest"];
            };
        };
        responses: {
            /** @description Existing or newly created mock server */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateMockResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getSpectralRuleset: {
        parameters: {
            query?: never;
            header: {
                "X-Org-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ruleset content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpectralRulesetResponse"];
                };
            };
        };
    };
    putSpectralRuleset: {
        parameters: {
            query?: never;
            header: {
                "X-Org-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutSpectralRulesetRequest"];
            };
        };
        responses: {
            /** @description Status response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Plan restriction */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    publishCliSpec: {
        parameters: {
            query?: never;
            header: {
                "X-Org-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CliPublishRequest"];
            };
        };
        responses: {
            /** @description Publish result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliPublishResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Version conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
